# Generated by Django 4.2.16 on 2024-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_alter_warhouses_cislo_skladu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='adresa_bydliska_sidlo',
            field=models.CharField(max_length=255, null=True, verbose_name='Adresa bydliska / sídlo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='datum_narodenia',
            field=models.DateField(null=True, verbose_name='Dátum narodenia'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dic',
            field=models.CharField(max_length=10, null=True, verbose_name='DIČ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ic_dph',
            field=models.CharField(max_length=20, null=True, verbose_name='IČ DPH'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ico',
            field=models.CharField(max_length=8, null=True, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='users',
            name='meno_nazov',
            field=models.CharField(max_length=255, null=True, verbose_name='Meno / Nazov'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tel_cislo_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel. číslo 2'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zastupeny',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zastúpený'),
        ),
    ]
