# Generated by Django 4.2.16 on 2024-12-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sklad', '0002_alter_prenajimatel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=11111, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_aktualna',
            field=models.CharField(blank=True, verbose_name='Zmluva (aktuálna)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_aktualna_2',
            field=models.CharField(blank=True, verbose_name='Zmluva (aktuálna) 2'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_aktualna_3',
            field=models.CharField(blank=True, verbose_name='Zmluva (aktuálna) 3'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_aktualna_4',
            field=models.CharField(blank=True, verbose_name='Zmluva (aktuálna) 4'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_minula_1',
            field=models.CharField(blank=True, verbose_name='Zmluva (minula) 1'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_minula_2',
            field=models.CharField(blank=True, verbose_name='Zmluva (minula) 2'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_minula_3',
            field=models.CharField(blank=True, verbose_name='Zmluva (minula) 3'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_minula_4',
            field=models.CharField(blank=True, verbose_name='Zmluva (minula) 4'),
        ),
        migrations.AlterField(
            model_name='users',
            name='zmluva_minula_5',
            field=models.CharField(blank=True, verbose_name='Zmluva (minula) 5'),
        ),
    ]
