# Generated by Django 4.2.16 on 2024-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_alter_warhouses_datum_dostupnosti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warhouses',
            name='cislo_skladu',
            field=models.CharField(max_length=100, verbose_name='Číslo skladu'),
        ),
    ]
